env: "sim"
gpu: true
fps_filter_ratio: 0.9
target_label: "stop sign"
pid_param_base: 0.6
dist_filter_ratio: 0.0
xy_max_err: 0.2
xyz_max_err_before_landing: 0.2
target_altitude_from_target: 0.25
starting_altitude: 2.5
auto_arm_offboard: True
search_dist: 2.0
target_maxdist: 2.0
extra_inferencing_delay: 0.0
