env: "live"
arrive_maxdist: 0.3
pid_param_base: 0.5
dist_filter_ratio: 0.5
xy_max_err: 0.15
xyz_max_err_before_landing: 0.12
target_altitude_from_target: 0.25
starting_altitude: 1.0
pose_rate: 10
search_dist: 0.3